# docker-compose.yml para configurar o PostgreSQL
version: '3.8'

services:
  postgres:
    build: .docker/postgres
    container_name: fleet_db
    environment:
      POSTGRES_DB: fleetdb
      POSTGRES_USER: fleetuser
      POSTGRES_PASSWORD: fleetpass
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres_data:/var/lib/postgresql/data
    networks:
      - fleet-network

networks:
  fleet-network: 
    driver: bridge
